---
description: Delete threat IP from firewall policy table 
name: delete_firewall_policy
pack: xmc
ref: xmc.delete_firewall_policy
tags: []
type:
  ref: standard
  parameters:
enabled: true

trigger:
  ref: standard
  type: core.st2.webhook
  parameters:
    url: delete_firewall_policy
criteria: {}
action:
  ref: xmc.delete_firewall_policy
  parameters:
    threat_ip: '{{trigger.body.threat_ip}}'
