#!/bin/bash
#
# networkingreconfig:  Re-configure network with new IP/FQDN/DNS
# 
# chkconfig: 2345 9 03
# description: Re-configure network with new IP/FQDN/DNS

python /opt/xmc/ova/bin/XMCPostIntall.py
cd /etc/init.d/
sysv-rc-conf xmc_postinstall off

